apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: auth-jwt
spec:
  snippets:
    - context: http.server
      value: location = /_auth/_jwks_uri { internal;return 200 '{"keys":[{"k":"ZmFudGFzdGljand0","kty":"oct","kid":"0001"}]}'; }
    - context: http.server.location
      value: auth_jwt "JWT token required";auth_jwt_type signed;auth_jwt_key_request /_auth/_jwks_uri;
