local-address=0.0.0.0
local-port=10053

daemon=no
guardian=no

launch=gpgsql
gpgsql-host=postgres.powerdns.svc.cluster.local
gpgsql-port=5432
gpgsql-user=powerdns
gpgsql-dbname=powerdns
gpgsql-password=SAMPLE_PSQL_PASSWORD

api=yes
api-key=SAMPLE-PDNS-API-SECRET

webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0
